[application]
name = "GroupCtrl"
default_platform = "desktop"

[bundle]
identifier = "dev.brodmo.groupctrl"
publisher = "Moritz Brödel"
icon = ["assets/icons/icon.icns"]

# Dioxus ignores this -> bug, fix via just patch-plist
[macos.plist]
LSUIElement = true
