groups:
- name: Web
  hotkey: null

  apps:
  - com.brave.Browser
  - com.markmcguill.strongbox.mac
- name: Files
  hotkey: Cmd+Opt+Ctrl+F

  apps:
  - com.apple.finder
  - com.apple.Preview
  - com.sublimetext.4
  - com.microsoft.Excel
- name: Programming
  hotkey: null

  apps:
  - com.jetbrains.intellij
  - com.jetbrains.pycharm
  - com.jetbrains.rustrover
- name: Terminal
  hotkey: null

  apps: []
- name: Notes
  hotkey: null

  apps:
  - com.anthropic.claudefordesktop
- name: Todos
  hotkey: null

  apps: []
- name: AI
  hotkey: null

  apps: []
- name: Music
  hotkey: Cmd+D

  apps:
  - com.spotify.client
